'use client';

import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { employeesApi } from '@/lib/api/employees';
import { leadIntegrationsApi, type IntegrationProvider, type IntegrationSettings } from '@/lib/api/leadIntegrations';
import { useAuthStore } from '@/store/authStore';

const TABS = ['Overview', 'Meta Ads', 'WhatsApp Ads', 'Email Accounts', 'Email Campaigns', 'Lead Routing', 'Import History', 'Automation Settings'] as const;
type Tab = typeof TABS[number];
const inputClass = 'min-h-11 w-full rounded-xl border border-gray-200 bg-white px-3 text-sm outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100';
const buttonClass = 'min-h-11 rounded-xl bg-indigo-600 px-4 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50';
function title(value: string) { return value.replaceAll('_', ' ').replace(/\b\w/g, (char) => char.toUpperCase()); }
function Panel({ children, className = '' }: { children: ReactNode; className?: string }) { return <section className={`rounded-2xl border border-gray-100 bg-white p-4 shadow-sm sm:p-5 ${className}`}>{children}</section>; }
function Empty({ children }: { children: ReactNode }) { return <div className="rounded-xl border border-dashed border-gray-200 p-8 text-center text-sm text-gray-500">{children}</div>; }
function Badge({ value }: { value: string }) { const good = ['active', 'imported', 'linked'].includes(value); return <span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${good ? 'bg-emerald-50 text-emerald-700' : value === 'failed' ? 'bg-red-50 text-red-700' : 'bg-amber-50 text-amber-700'}`}>{title(value)}</span>; }

export default function LeadIntegrationsPage() {
  const qc = useQueryClient();
  const { isAdmin } = useAuthStore();
  const canManage = isAdmin();
  const [tab, setTab] = useState<Tab>('Overview');
  const [filters, setFilters] = useState({ provider: '', campaign_id: '', assigned_to: '', country: '', lead_status: '', date_from: '', date_to: '' });
  const overview = useQuery({ queryKey: ['lead-integrations', filters], queryFn: () => leadIntegrationsApi.overview(Object.fromEntries(Object.entries(filters).filter(([, value]) => value))) });
  const history = useQuery({ queryKey: ['lead-integrations-history'], queryFn: () => leadIntegrationsApi.history(), enabled: tab === 'Import History' });
  const reviews = useQuery({ queryKey: ['lead-integrations-review'], queryFn: leadIntegrationsApi.reviewQueue, enabled: canManage && tab === 'Overview' });
  const employees = useQuery({ queryKey: ['employees', 'lead-integrations'], queryFn: () => employeesApi.list(), enabled: canManage });
  const refresh = () => { qc.invalidateQueries({ queryKey: ['lead-integrations'] }); qc.invalidateQueries({ queryKey: ['lead-integrations-history'] }); qc.invalidateQueries({ queryKey: ['lead-integrations-review'] }); };
  const connection = useMutation({ mutationFn: leadIntegrationsApi.createInboundEmail, onSuccess: refresh });
  const disconnect = useMutation({ mutationFn: leadIntegrationsApi.disconnect, onSuccess: refresh });
  const campaign = useMutation({ mutationFn: leadIntegrationsApi.createCampaign, onSuccess: refresh });
  const deleteCampaign = useMutation({ mutationFn: leadIntegrationsApi.deleteCampaign, onSuccess: refresh });
  const rule = useMutation({ mutationFn: leadIntegrationsApi.createRule, onSuccess: refresh });
  const deleteRule = useMutation({ mutationFn: leadIntegrationsApi.deleteRule, onSuccess: refresh });
  const resolveReview = useMutation({ mutationFn: ({ id, payload }: { id: number; payload: Record<string, unknown> }) => leadIntegrationsApi.resolveReview(id, payload), onSuccess: refresh });
  const data = overview.data;

  const oauth = async (provider: 'meta' | 'google' | 'microsoft') => {
    const result = await leadIntegrationsApi.oauthUrl(provider);
    window.location.assign(result.authorization_url);
  };
  const submitEmail = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    connection.mutate({ provider: 'email', name: form.get('name'), account_email: form.get('account_email'), authorized_senders: String(form.get('authorized_senders') || '').split(',').map((item) => item.trim()).filter(Boolean), receiving_aliases: String(form.get('receiving_aliases') || '').split(',').map((item) => item.trim()).filter(Boolean) });
    event.currentTarget.reset();
  };
  const submitCampaign = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    campaign.mutate({ platform: form.get('platform'), name: form.get('name'), external_id: form.get('external_id') || null, assigned_to: Number(form.get('assigned_to')) || null, status: 'active', service: form.get('service') || null, target_market: form.get('target_market') || null });
    event.currentTarget.reset();
  };
  const submitRule = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    rule.mutate({ name: form.get('name'), source_type: form.get('source_type'), source_key: form.get('source_key') || null, strategy: form.get('strategy'), assigned_to: Number(form.get('assigned_to')) || null, backup_user_id: Number(form.get('backup_user_id')) || null, priority: Number(form.get('priority')) || 100, is_active: true });
    event.currentTarget.reset();
  };

  if (overview.isLoading) return <div className="h-72 animate-pulse rounded-2xl bg-gray-100" />;
  if (overview.isError || !data) return <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">Lead Integrations could not be loaded. Apply the new module migration before opening this page.</div>;

  const providerConnections = (provider: IntegrationProvider) => data.connections.filter((item) => item.provider === provider);
  return <div className="min-w-0 space-y-5">
    <div><h1 className="text-xl font-bold text-gray-900">Lead Integrations & Campaign Automation</h1><p className="mt-1 text-xs text-gray-500">Capture campaign enquiries into the existing Leads module with controlled routing and review.</p></div>
    <div className="-mx-1 overflow-x-auto px-1 pb-1"><div className="flex min-w-max gap-1 rounded-xl bg-gray-100 p-1">{TABS.map((item) => <button key={item} onClick={() => setTab(item)} className={`min-h-10 whitespace-nowrap rounded-lg px-3 text-xs font-semibold ${tab === item ? 'bg-white text-indigo-700 shadow-sm' : 'text-gray-500'}`}>{item}</button>)}</div></div>

    {tab === 'Overview' && <div className="space-y-5">
      <Panel><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><select value={filters.provider} onChange={(event) => setFilters({ ...filters, provider: event.target.value })} className={inputClass}><option value="">All platforms</option>{['meta', 'whatsapp', 'google', 'microsoft', 'email'].map((item) => <option key={item} value={item}>{title(item)}</option>)}</select><select value={filters.campaign_id} onChange={(event) => setFilters({ ...filters, campaign_id: event.target.value })} className={inputClass}><option value="">All campaigns</option>{data.campaigns.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>{canManage && <select value={filters.assigned_to} onChange={(event) => setFilters({ ...filters, assigned_to: event.target.value })} className={inputClass}><option value="">All employees</option>{employees.data?.map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select>}<input value={filters.country} onChange={(event) => setFilters({ ...filters, country: event.target.value })} placeholder="Country" className={inputClass} /><select value={filters.lead_status} onChange={(event) => setFilters({ ...filters, lead_status: event.target.value })} className={inputClass}><option value="">All lead statuses</option>{['new', 'contacted', 'ringing', 'important', 'converted', 'lost', 'followup', 'meeting', 'not_interested'].map((item) => <option key={item} value={item}>{title(item)}</option>)}</select><input type="date" value={filters.date_from} onChange={(event) => setFilters({ ...filters, date_from: event.target.value })} className={inputClass} /><input type="date" value={filters.date_to} onChange={(event) => setFilters({ ...filters, date_to: event.target.value })} className={inputClass} /><button onClick={() => setFilters({ provider: '', campaign_id: '', assigned_to: '', country: '', lead_status: '', date_from: '', date_to: '' })} className="min-h-11 rounded-xl border border-gray-200 px-4 text-sm font-semibold text-gray-600">Clear filters</button></div></Panel>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6">{[
        ['Meta Leads', data.summary.meta_leads], ['Email Leads', data.summary.email_leads], ['Campaign Replies', data.summary.campaign_replies],
        ['Requires Review', data.summary.review_required], ['Assigned', data.summary.assigned], ['Deals Won', data.summary.deals_won],
      ].map(([label, value]) => <Panel key={label}><p className="text-[11px] font-semibold uppercase tracking-wide text-gray-500">{label}</p><p className="mt-2 text-2xl font-bold text-gray-900">{value}</p></Panel>)}</div>
      <Panel><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold text-gray-900">Review Queue</h2><p className="text-xs text-gray-500">Imports that need a human decision</p></div></div>{!canManage ? <p className="text-sm text-gray-500">Only an owner or admin can review unassigned source content.</p> : reviews.data?.length ? <div className="grid gap-3 lg:grid-cols-2">{reviews.data.map((item) => <article key={item.id} className="rounded-xl border border-gray-100 p-4"><div className="flex items-start justify-between gap-2"><div><p className="font-semibold text-gray-900">{title(item.reason)}</p><p className="mt-1 text-xs text-gray-500">{item.event?.provider} · {item.event?.event_type}</p></div><Badge value={item.status} /></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={() => resolveReview.mutate({ id: item.id, payload: { action: 'retry' } })} className="min-h-10 rounded-xl bg-indigo-600 px-3 text-xs font-semibold text-white">Retry</button><button onClick={() => resolveReview.mutate({ id: item.id, payload: { action: 'reject', notes: 'Rejected from review queue' } })} className="min-h-10 rounded-xl border border-red-200 px-3 text-xs font-semibold text-red-600">Reject</button></div></article>)}</div> : <Empty>No source records currently require review.</Empty>}</Panel>
    </div>}

    {tab === 'Meta Ads' && <div className="space-y-4"><ProviderHeader title="Meta Lead Ads" ready={data.provider_readiness.meta} canManage={canManage} onConnect={() => oauth('meta')} />{providerConnections('meta').length ? <ConnectionList connections={providerConnections('meta')} onDisconnect={(id) => disconnect.mutate(id)} canManage={canManage} /> : <Empty>No Facebook Page is connected. Configure server credentials, then connect an authorized Meta Business account.</Empty>}<Panel><h2 className="font-bold text-gray-900">Historical Instant Form sync</h2><p className="mt-1 text-xs text-gray-500">Use a form ID and an explicit accessible date range. Repeat runs skip existing Meta lead IDs.</p>{canManage && providerConnections('meta').length > 0 && <MetaHistoryForm connections={providerConnections('meta')} onSaved={refresh} />}<p className="mt-3 rounded-xl bg-amber-50 p-3 text-xs text-amber-800">Meta permissions and Page/Form access must be approved before live leads can be retrieved. The CRM does not assume ad-account access grants Page lead access.</p></Panel></div>}

    {tab === 'WhatsApp Ads' && <div className="space-y-4"><ProviderHeader title="Click-to-WhatsApp Ads" ready={false} canManage={false} /><Panel><h2 className="font-bold text-gray-900">Not connected</h2><p className="mt-2 text-sm text-gray-600">This remains disabled until official WhatsApp Business Platform credentials, the number&apos;s Coexistence eligibility, permissions, and expected charges are verified. Your current WhatsApp Business mobile app and number are not changed.</p><ul className="mt-4 list-disc space-y-1 pl-5 text-xs text-gray-500"><li>No WhatsApp Web scraping or unofficial automation is used.</li><li>Only messages carrying reliable Click-to-WhatsApp referral metadata qualify for automatic campaign attribution.</li><li>General conversations are not automatically converted into campaign leads.</li></ul></Panel></div>}

    {tab === 'Email Accounts' && <div className="space-y-4"><div className="grid gap-3 md:grid-cols-2"><ProviderHeader title="Google Workspace / Gmail" ready={data.provider_readiness.google} canManage={canManage} onConnect={() => oauth('google')} /><ProviderHeader title="Microsoft 365 / Outlook" ready={data.provider_readiness.microsoft} canManage={canManage} onConnect={() => oauth('microsoft')} /></div><ConnectionList connections={data.connections.filter((item) => ['google', 'microsoft', 'email'].includes(item.provider))} onDisconnect={(id) => disconnect.mutate(id)} canManage={canManage} />{canManage && <Panel><h2 className="font-bold text-gray-900">Approved forwarded-lead inbox</h2><p className="mt-1 text-xs text-gray-500">Register an inbound provider endpoint and restrict it to approved senders. Addresses are comma-separated.</p><form onSubmit={submitEmail} className="mt-4 grid gap-3 md:grid-cols-2"><input name="name" required placeholder="Connection name" className={inputClass} /><input name="account_email" required type="email" placeholder="lead-inbox@company.com" className={inputClass} /><input name="authorized_senders" required placeholder="sender1@company.com, sender2@company.com" className={inputClass} /><input name="receiving_aliases" placeholder="employee-a-leads@company.com" className={inputClass} /><button disabled={connection.isPending} className={`${buttonClass} md:col-span-2`}>Create approved inbound endpoint</button></form></Panel>}</div>}

    {tab === 'Email Campaigns' && <div className="space-y-4">{canManage && <Panel><h2 className="font-bold text-gray-900">Register campaign metadata</h2><p className="mt-1 text-xs text-gray-500">Reliable reply attribution requires sender message/thread identifiers or an imported recipient registry; a subject match alone is never considered sufficient.</p><form onSubmit={submitCampaign} className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><select name="platform" className={inputClass}><option value="email">Other approved email</option><option value="google">Gmail</option><option value="microsoft">Microsoft 365</option><option value="meta">Meta</option></select><input name="name" required placeholder="Campaign name" className={inputClass} /><input name="external_id" placeholder="External campaign ID" className={inputClass} /><select name="assigned_to" className={inputClass}><option value="">Review queue</option>{employees.data?.map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select><input name="service" placeholder="Associated service" className={inputClass} /><input name="target_market" placeholder="Target market" className={inputClass} /><button className={`${buttonClass} sm:col-span-2 lg:col-span-3`}>Register campaign</button></form></Panel>}<div className="grid gap-3 lg:grid-cols-2">{data.campaigns.length ? data.campaigns.map((item) => <Panel key={item.id}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-indigo-600">{item.platform}</p><h2 className="mt-1 font-bold text-gray-900">{item.name}</h2><p className="mt-1 text-xs text-gray-500">{item.external_id || 'No external ID'} · {item.assigned_to?.name || 'Review queue'}</p></div><Badge value={item.status} /></div>{canManage && <button onClick={() => deleteCampaign.mutate(item.id)} className="mt-4 text-xs font-semibold text-red-600">Remove registry entry</button>}</Panel>) : <Empty>No campaigns registered.</Empty>}</div></div>}
    {tab === 'Email Campaigns' && canManage && data.campaigns.length > 0 && <RecipientImport campaigns={data.campaigns} onSaved={refresh} />}

    {tab === 'Lead Routing' && <div className="space-y-4">{canManage && <Panel><h2 className="font-bold text-gray-900">Add routing rule</h2><p className="mt-1 text-xs text-gray-500">Existing lead ownership always wins. Lower priority numbers run first.</p><form onSubmit={submitRule} className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><input name="name" required placeholder="Rule name" className={inputClass} /><select name="source_type" className={inputClass}>{['campaign', 'ad', 'form', 'alias', 'mailbox', 'authorized_sender', 'provider', 'default'].map((item) => <option key={item} value={item}>{title(item)}</option>)}</select><input name="source_key" placeholder="Exact source ID / address" className={inputClass} /><select name="strategy" className={inputClass}><option value="fixed">Fixed employee</option><option value="round_robin">Round robin (team required via API)</option></select><select name="assigned_to" className={inputClass}><option value="">Unassigned review</option>{employees.data?.map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select><select name="backup_user_id" className={inputClass}><option value="">No backup</option>{employees.data?.map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select><input name="priority" type="number" min="1" defaultValue="100" className={inputClass} /><button className={`${buttonClass} sm:col-span-2`}>Save routing rule</button></form></Panel>}<div className="grid gap-3 lg:grid-cols-2">{data.routing_rules.length ? data.routing_rules.map((item) => <Panel key={item.id}><div className="flex justify-between gap-3"><div><h2 className="font-bold text-gray-900">{item.name}</h2><p className="mt-1 text-xs text-gray-500">{title(item.source_type)}: {item.source_key || 'Any'} · {title(item.strategy)}</p><p className="mt-1 text-xs text-gray-500">Owner: {item.assigned_to?.name || 'Review queue'} · Priority {item.priority}</p></div><Badge value={item.is_active ? 'active' : 'paused'} /></div>{canManage && <button onClick={() => deleteRule.mutate(item.id)} className="mt-4 text-xs font-semibold text-red-600">Delete rule</button>}</Panel>) : <Empty>No routing rules configured.</Empty>}</div></div>}

    {tab === 'Import History' && <Panel><h2 className="mb-4 font-bold text-gray-900">Import History</h2>{history.isLoading ? <div className="h-40 animate-pulse rounded-xl bg-gray-100" /> : history.data?.length ? <div className="grid gap-3">{history.data.map((item) => <article key={item.id} className="grid gap-3 rounded-xl border border-gray-100 p-4 sm:grid-cols-[1fr_auto] sm:items-center"><div className="min-w-0"><p className="font-semibold text-gray-900">{title(item.event_type)}</p><p className="mt-1 break-words text-xs text-gray-500">{item.provider} · {item.campaign?.name || 'No matched campaign'} · {item.assigned_to?.name || 'Unassigned'} · {new Date(item.created_at).toLocaleString()}</p>{item.error_message && <p className="mt-2 text-xs text-red-600">{item.error_message}</p>}</div><Badge value={item.status} /></article>)}</div> : <Empty>No integration events have been received.</Empty>}</Panel>}

    {tab === 'Automation Settings' && <SettingsPanel settings={data.settings} canManage={canManage} employees={employees.data || []} onSaved={refresh} />}
  </div>;
}

function ProviderHeader({ title: heading, ready, canManage, onConnect }: { title: string; ready: boolean; canManage: boolean; onConnect?: () => void }) {
  return <Panel><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold text-gray-900">{heading}</h2><p className={`mt-1 text-xs ${ready ? 'text-emerald-600' : 'text-amber-600'}`}>{ready ? 'Server credentials configured' : 'Server configuration required'}</p></div>{canManage && onConnect && <button onClick={onConnect} disabled={!ready} className={buttonClass}>Connect account</button>}</div></Panel>;
}
function MetaHistoryForm({ connections, onSaved }: { connections: Array<{ id: number; name: string }>; onSaved: () => void }) {
  const sync = useMutation({ mutationFn: ({ id, payload }: { id: number; payload: { form_id: string; date_from: string; date_to: string } }) => leadIntegrationsApi.syncMetaHistory(id, payload), onSuccess: onSaved });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); sync.mutate({ id: Number(form.get('connection_id')), payload: { form_id: String(form.get('form_id')), date_from: String(form.get('date_from')), date_to: String(form.get('date_to')) } }); };
  return <form onSubmit={submit} className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><select name="connection_id" className={inputClass}>{connections.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input name="form_id" required placeholder="Meta form ID" className={inputClass} /><input name="date_from" required type="date" className={inputClass} /><input name="date_to" required type="date" className={inputClass} /><button disabled={sync.isPending} className={`${buttonClass} sm:col-span-2 lg:col-span-4`}>Queue accessible history</button></form>;
}
function RecipientImport({ campaigns, onSaved }: { campaigns: Array<{ id: number; name: string }>; onSaved: () => void }) {
  const [error, setError] = useState('');
  const mutation = useMutation({ mutationFn: ({ id, recipients }: { id: number; recipients: Array<{ email: string; message_id?: string; thread_id?: string; lead_id?: number }> }) => leadIntegrationsApi.registerRecipients(id, recipients), onSuccess: () => { setError(''); onSaved(); } });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const recipients = String(form.get('recipients') || '').split('\n').map((line) => line.trim()).filter(Boolean).map((line) => { const [email, message_id, thread_id, leadId] = line.split(',').map((part) => part.trim()); return { email, message_id: message_id || undefined, thread_id: thread_id || undefined, lead_id: Number(leadId) || undefined }; }); if (recipients.some((row) => !row.email || (!row.message_id && !row.thread_id))) { setError('Each line needs an email and either Message-ID or thread ID.'); return; } mutation.mutate({ id: Number(form.get('campaign_id')), recipients }); };
  return <Panel><h2 className="font-bold text-gray-900">Import campaign recipient identities</h2><p className="mt-1 text-xs text-gray-500">One line per recipient: email, outbound Message-ID, provider thread ID, optional existing CRM lead ID. Message-ID or thread ID is mandatory.</p><form onSubmit={submit} className="mt-4 space-y-3"><select name="campaign_id" className={inputClass}>{campaigns.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><textarea name="recipients" required rows={5} placeholder="prospect@example.com,&lt;outbound-message-id&gt;,provider-thread-id,123" className="w-full rounded-xl border border-gray-200 p-3 font-mono text-xs outline-none focus:border-indigo-400" />{error && <p className="text-xs text-red-600">{error}</p>}<button disabled={mutation.isPending} className={buttonClass}>Import recipient identities</button></form></Panel>;
}
function ConnectionList({ connections, onDisconnect, canManage }: { connections: Array<{ id: number; name: string; provider: string; status: string; account_email?: string | null; last_synced_at?: string | null; last_error?: string | null }>; onDisconnect: (id: number) => void; canManage: boolean }) {
  if (!connections.length) return null;
  return <div className="grid gap-3 lg:grid-cols-2">{connections.map((item) => <Panel key={item.id}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-semibold uppercase text-indigo-600">{item.provider}</p><h3 className="mt-1 truncate font-bold text-gray-900">{item.name}</h3><p className="mt-1 truncate text-xs text-gray-500">{item.account_email || 'Provider account'} · Last sync: {item.last_synced_at ? new Date(item.last_synced_at).toLocaleString() : 'Not yet'}</p>{item.last_error && <p className="mt-2 text-xs text-red-600">{item.last_error}</p>}</div><Badge value={item.status} /></div>{canManage && item.status !== 'disconnected' && <button onClick={() => onDisconnect(item.id)} className="mt-4 text-xs font-semibold text-red-600">Disconnect</button>}</Panel>)}</div>;
}
function SettingsPanel({ settings, canManage, employees, onSaved }: { settings: IntegrationSettings | null; canManage: boolean; employees: Array<{ id: number; name: string }>; onSaved: () => void }) {
  const [form, setForm] = useState<IntegrationSettings | null>(settings);
  const [mappingText, setMappingText] = useState(JSON.stringify(settings?.field_mappings || { meta: {} }, null, 2));
  const [mappingError, setMappingError] = useState('');
  useEffect(() => { setForm(settings); setMappingText(JSON.stringify(settings?.field_mappings || { meta: {} }, null, 2)); }, [settings]);
  const save = useMutation({ mutationFn: leadIntegrationsApi.updateSettings, onSuccess: onSaved });
  if (!canManage || !form) return <Panel><p className="text-sm text-gray-500">Only an owner or admin can change integration automation settings.</p></Panel>;
  const toggle = (key: keyof IntegrationSettings) => setForm({ ...form, [key]: !form[key] });
  const saveSettings = () => { try { const field_mappings = JSON.parse(mappingText) as Record<string, unknown>; setMappingError(''); save.mutate({ ...form, field_mappings }); } catch { setMappingError('Field mappings must be valid JSON.'); } };
  return <Panel><h2 className="font-bold text-gray-900">Automation Settings</h2><p className="mt-1 text-xs text-gray-500">Disabling a source stops future imports; it never deletes historical leads.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{[
    ['meta_enabled', 'Meta Instant Form imports'], ['email_enabled', 'Email imports and replies'], ['auto_import_enabled', 'Automatically import valid leads'], ['review_unmatched', 'Send unmatched records to review'],
  ].map(([key, label]) => <label key={key} className="flex min-h-12 items-center justify-between rounded-xl border border-gray-200 px-3 text-sm font-medium"><span>{label}</span><input type="checkbox" checked={Boolean(form[key as keyof IntegrationSettings])} onChange={() => toggle(key as keyof IntegrationSettings)} /></label>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold text-gray-600">Default owner<select value={form.default_owner_id || ''} onChange={(event) => setForm({ ...form, default_owner_id: Number(event.target.value) || null })} className={`${inputClass} mt-1`}><option value="">Review queue</option>{employees.map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select></label><label className="text-xs font-semibold text-gray-600">Raw source retention (days)<input type="number" min="1" max="365" value={form.raw_content_retention_days} onChange={(event) => setForm({ ...form, raw_content_retention_days: Number(event.target.value) })} className={`${inputClass} mt-1`} /></label></div><label className="mt-4 block text-xs font-semibold text-gray-600">Provider field mappings (JSON)<textarea value={mappingText} onChange={(event) => setMappingText(event.target.value)} rows={6} spellCheck={false} className="mt-1 w-full rounded-xl border border-gray-200 p-3 font-mono text-xs outline-none focus:border-indigo-400" /></label>{mappingError && <p className="mt-2 text-xs text-red-600">{mappingError}</p>}<div className="mt-4 rounded-xl bg-gray-50 p-3 text-xs text-gray-500">WhatsApp activation is deliberately locked until an official connection has verified Coexistence eligibility. Raw secrets and OAuth tokens are never displayed here.</div><button onClick={saveSettings} disabled={save.isPending} className={`${buttonClass} mt-4`}>Save settings</button></Panel>;
}
